# Generated by Django 5.2.6 on 2025-09-13 04:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "author_nickname",
                    models.CharField(default="익명", max_length=50, verbose_name="닉네임"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="조회수"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=True, verbose_name="익명여부"),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="좋아요 수"),
                ),
                (
                    "dislikes_count",
                    models.PositiveIntegerField(default=0, verbose_name="싫어요 수"),
                ),
            ],
            options={
                "verbose_name": "게시글",
                "verbose_name_plural": "게시글들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="댓글 내용")),
                (
                    "author_nickname",
                    models.CharField(default="익명", max_length=50, verbose_name="닉네임"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "is_anonymous",
                    models.BooleanField(default=True, verbose_name="익명여부"),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="좋아요 수"),
                ),
                (
                    "dislikes_count",
                    models.PositiveIntegerField(default=0, verbose_name="싫어요 수"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="board.post",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글들",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommentReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=100, verbose_name="세션 ID")),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[("like", "좋아요"), ("dislike", "싫어요")],
                        max_length=10,
                        verbose_name="반응 타입",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="board.comment",
                        verbose_name="댓글",
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글 반응",
                "verbose_name_plural": "댓글 반응들",
                "unique_together": {("comment", "session_id")},
            },
        ),
        migrations.CreateModel(
            name="PostReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=100, verbose_name="세션 ID")),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[("like", "좋아요"), ("dislike", "싫어요")],
                        max_length=10,
                        verbose_name="반응 타입",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="board.post",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글 반응",
                "verbose_name_plural": "게시글 반응들",
                "unique_together": {("post", "session_id")},
            },
        ),
    ]
