# Generated by Django 5.2.6 on 2025-09-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="delete_password",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="삭제 비밀번호"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="삭제일"),
        ),
        migrations.AddField(
            model_name="post",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="삭제 여부"),
        ),
    ]
