# Generated by Django 5.2.6 on 2025-09-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_post_delete_password_post_deleted_at_post_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="dislikes_count",
        ),
        migrations.RemoveField(
            model_name="post",
            name="dislikes_count",
        ),
        migrations.AddField(
            model_name="comment",
            name="hearts_count",
            field=models.PositiveIntegerField(default=0, verbose_name="하트 수"),
        ),
        migrations.AddField(
            model_name="comment",
            name="laughs_count",
            field=models.PositiveIntegerField(default=0, verbose_name="웃음 수"),
        ),
        migrations.AddField(
            model_name="comment",
            name="sads_count",
            field=models.PositiveIntegerField(default=0, verbose_name="슬픔 수"),
        ),
        migrations.AddField(
            model_name="comment",
            name="wows_count",
            field=models.PositiveIntegerField(default=0, verbose_name="놀람 수"),
        ),
        migrations.AddField(
            model_name="post",
            name="hearts_count",
            field=models.PositiveIntegerField(default=0, verbose_name="하트 수"),
        ),
        migrations.AddField(
            model_name="post",
            name="laughs_count",
            field=models.PositiveIntegerField(default=0, verbose_name="웃음 수"),
        ),
        migrations.AddField(
            model_name="post",
            name="sads_count",
            field=models.PositiveIntegerField(default=0, verbose_name="슬픔 수"),
        ),
        migrations.AddField(
            model_name="post",
            name="wows_count",
            field=models.PositiveIntegerField(default=0, verbose_name="놀람 수"),
        ),
        migrations.AlterField(
            model_name="commentreaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("like", "좋아요"),
                    ("heart", "하트"),
                    ("laugh", "웃음"),
                    ("wow", "놀람"),
                    ("sad", "슬픔"),
                ],
                max_length=10,
                verbose_name="반응 타입",
            ),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("like", "좋아요"),
                    ("heart", "하트"),
                    ("laugh", "웃음"),
                    ("wow", "놀람"),
                    ("sad", "슬픔"),
                ],
                max_length=10,
                verbose_name="반응 타입",
            ),
        ),
    ]
