# Generated by Django 5.2.6 on 2025-09-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_remove_comment_dislikes_count_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="commentreaction",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="postreaction",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="commentreaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("heart", "하트"),
                    ("laugh", "웃음"),
                    ("wow", "놀람"),
                    ("sad", "슬픔"),
                ],
                max_length=10,
                verbose_name="반응 타입",
            ),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("heart", "하트"),
                    ("laugh", "웃음"),
                    ("wow", "놀람"),
                    ("sad", "슬픔"),
                ],
                max_length=10,
                verbose_name="반응 타입",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commentreaction",
            unique_together={("comment", "session_id", "reaction_type")},
        ),
        migrations.AlterUniqueTogether(
            name="postreaction",
            unique_together={("post", "session_id", "reaction_type")},
        ),
    ]
